---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    author: intelliqit
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30009
  selector:
    type: ci-cd
    author: intelliqit
  




